.TH debianize 1 "2004-09-10" "logilab devtools"

.SH NAME
debianize \- automatic maintenance of a package's debian files


.SH SYNOPSIS
.B debianize
.RI [ options ]
.br

.SH DESCRIPTION
Part of logilab's devtools.

.SH LICENCE
(c) 2004 Logilab. General Public Licence.

.SH SEE ALSO
/usr/share/doc/pythonX.Y-devtools/

.SH AUTHOR
Logilab <contact@logilab.fr>
