.TH lgp 1 "2006-08-01" "logilab-packaging"

.SH NAME
lgp \- logilab packaging tool to ease projects' maintenance


.SH SYNOPSIS
.B lgp command
.RI [ options ]
.br

.SH DESCRIPTION
Try lgp -h for more information.

.SH LICENCE
(c) 2006 Logilab. General Public Licence.

.SH SEE ALSO
pycoverage(1)

.SH AUTHOR
Logilab <contact@logilab.fr>
