#!/bin/sh
# invoke shell if build fails.

# DISABLED BY DEFAULT. NOT WELL TESTED
exit 0

apt-get install -y --force-yes vim less bash
cd /tmp/buildd/*/debian/..
/bin/bash < /dev/tty > /dev/tty 2> /dev/tty
