#!/bin/sh

# repository is not always existing for all images
# consider index files as optional and exit with error status
set +e

apt-get install -y --force-yes wget >/dev/null 2>&1
wget -q http://ftp.logilab.org/dists/logilab-dists-key.asc  -O - | apt-key add -
