#!/bin/sh

cat > /etc/apt/apt.conf.d/99lgp <<EOF
APT {
  Get {
    Assume-Yes "true";
    Fix-Broken "true";
    Force-Yes "true";
  };
  Clean "always";
  AllowUnauthenticated "true";
  ReInstall "true";
};

// Pre-configure all packages before
// they are installed.
DPkg::Pre-Install-Pkgs {
  "dpkg-preconfigure --apt --priority=low";
};
EOF

cat > /etc/apt/preferences.d/default-lgp <<EOF

Package: *
Pin: release o=Debian,n=$DIST
Pin-Priority: 980

Package: *
Pin: release n=$DIST-backports
Pin-Priority: 990

Package: *
Pin: release a=acceptance
Pin-Priority: 990

EOF
